# Generated by Django 5.2.1 on 2025-07-17 23:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apellido', models.CharField(max_length=100)),
                ('nombre', models.CharField(max_length=100)),
                ('domicilio', models.TextField()),
                ('cuil_dni', models.CharField(max_length=20, unique=True)),
                ('edad', models.PositiveIntegerField()),
                ('telefono', models.CharField(max_length=20)),
                ('con_quien_vive', models.CharField(max_length=100)),
                ('tipo_vivienda', models.CharField(choices=[('propia', 'Propia'), ('alquilada', 'Alquilada'), ('prestada', 'Prestada')], max_length=10)),
                ('tiene_beneficio', models.BooleanField(default=False)),
                ('cual_beneficio', models.TextField(blank=True, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
